# Generated by Django 5.1.1 on 2024-09-19 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Budget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.CharField(max_length=100, verbose_name="Бюджет")),
            ],
            options={
                "verbose_name": "Бюджет",
                "verbose_name_plural": "Бюджеты",
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Название")),
            ],
            options={
                "verbose_name": "Событие",
                "verbose_name_plural": "События",
            },
        ),
        migrations.CreateModel(
            name="Bouquet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="Цена"
                    ),
                ),
                ("description", models.TextField(verbose_name="Описание")),
                ("composition", models.TextField(verbose_name="Состав")),
                ("image", models.ImageField(upload_to="images/")),
                (
                    "size",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Размер"
                    ),
                ),
                ("events", models.ManyToManyField(blank=True, to="bouquet.event")),
            ],
            options={
                "verbose_name": "Букет",
                "verbose_name_plural": "Букеты",
            },
        ),
    ]
