# Generated by Django 5.1.1 on 2024-09-18 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Название")),
            ],
        ),
        migrations.CreateModel(
            name="Bouquet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="Цена"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW", "Новый"),
                            ("PAY", "Оплачен"),
                            ("CFM", "Подтвержден"),
                            ("COM", "Завершен"),
                        ],
                        db_index=True,
                        default="NEW",
                        max_length=3,
                        verbose_name="Статус",
                    ),
                ),
                ("composition_description", models.TextField(verbose_name="Состав")),
                ("image", models.ImageField(upload_to="images/")),
                (
                    "size_description",
                    models.CharField(max_length=100, verbose_name="Размер"),
                ),
                ("events", models.ManyToManyField(blank=True, to="bouquet.event")),
            ],
        ),
    ]
