# Generated by Django 5.1.1 on 2024-09-20 14:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bouquet', '0002_consultation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='order_accepted',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Заказ принят'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='registration_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Время регистрации'),
        ),
    ]
