# Generated by Django 5.1.1 on 2024-09-20 15:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bouquet', '0003_alter_consultation_order_accepted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=255)),
                ('order_time', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='consultation',
            name='registration_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 9, 20, 15, 4, 8, 59610, tzinfo=datetime.timezone.utc), null=True, verbose_name='Время регистрации'),
        ),
    ]
