# Generated by Django 5.1.1 on 2024-09-20 16:17

import datetime
import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bouquet', '0004_order_alter_consultation_registration_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AddField(
            model_name='order',
            name='bouquet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='bouquet.bouquet', verbose_name='Букет'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='consultation',
            name='registration_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 9, 20, 16, 17, 43, 135162, tzinfo=datetime.timezone.utc), null=True, verbose_name='Время регистрации'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='order',
            name='client_name',
            field=models.CharField(max_length=100, verbose_name='Имя клиента'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_time',
            field=models.CharField(max_length=50, verbose_name='Время доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Номер телефона'),
        ),
    ]
