# Generated by Django 5.1.1 on 2024-09-20 16:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bouquet', '0005_alter_order_options_order_bouquet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='registration_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 9, 20, 16, 20, 51, 328767, tzinfo=datetime.timezone.utc), null=True, verbose_name='Время регистрации'),
        ),
    ]
