# Generated by Django 5.1.1 on 2024-09-22 09:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bouquet", "0006_alter_consultation_registration_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("accepted", "Заказ оплачен"),
                    ("confirmed", "Заказ подтвержден"),
                    ("delivering", "Заказ доставляется"),
                    ("completed", "Выполнен"),
                ],
                default="accepted",
                max_length=20,
                verbose_name="Статус заказа",
            ),
        ),
        migrations.AlterField(
            model_name="consultation",
            name="registration_time",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(
                    2024, 9, 22, 9, 15, 29, 918303, tzinfo=datetime.timezone.utc
                ),
                null=True,
                verbose_name="Время регистрации",
            ),
        ),
    ]
